In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df1 = pd.read_csv('TrainDataset.csv')

In [3]:
df2 = pd.read_csv('TestDataset.csv')

In [4]:
df1.head()

STORY  SECTION
0  The roadshow and the filing of nomination pape...        0
1  These vulnerabilities could have allowed hacke...        1
2  "People will now be able to include music in t...        1
3  Jersey is expected to have a good start at the...        2
4  Xiaomi’s unveiling also hints at how Samsung i...        1

In [5]:
df2.head()

STORY
0  Privileged to have done this candid and COMPLE...
1  6) Some analysts expect volatility to remain h...
2  There is no stopping Marvel Cinematic Universe...
3  According to Ravi Menon, analyst at Elara Secu...
4  A complaint against Nadiadwala, known for prod...

# Number of Words

In [6]:
df1['Number_of_Words'] = df1['STORY'].apply(lambda x: len(str(x).split(" ")))

In [7]:
df1[['STORY','Number_of_Words']].head(n=15)

STORY  Number_of_Words
0   The roadshow and the filing of nomination pape...              152
1   These vulnerabilities could have allowed hacke...              176
2   "People will now be able to include music in t...               92
3   Jersey is expected to have a good start at the...               34
4   Xiaomi’s unveiling also hints at how Samsung i...              124
5   Analysts at Edelweiss Securities Ltd point out...               39
6   The directorial debut of Prithviraj Sukumaran ...               17
7   Chrome is the most popular web browser, with a...               65
8   "Maruti saw a sudden turn in its stock price a...              116
9   Centrum has also raised TCS target prices high...               80
10  While Mohanlal will play the titular role in B...               17
11  Consequently, there has been an explosive grow...              426
12  Expanding the 'document upload' feature on its...               77
13  Bose said it was decided at the Left Front mee...              146
14  Guglielmo Marchetti of Notorious Pictures and ...               24

# Number of Characters

In [8]:
df1['Number_of_char'] = df1['STORY'].str.len() 

In [9]:
df1[['STORY','Number_of_char']].head(n=20)

STORY  Number_of_char
0   The roadshow and the filing of nomination pape...             892
1   These vulnerabilities could have allowed hacke...            1083
2   "People will now be able to include music in t...             535
3   Jersey is expected to have a good start at the...             181
4   Xiaomi’s unveiling also hints at how Samsung i...             697
5   Analysts at Edelweiss Securities Ltd point out...             266
6   The directorial debut of Prithviraj Sukumaran ...             100
7   Chrome is the most popular web browser, with a...             372
8   "Maruti saw a sudden turn in its stock price a...             710
9   Centrum has also raised TCS target prices high...             533
10  While Mohanlal will play the titular role in B...             105
11  Consequently, there has been an explosive grow...            2727
12  Expanding the 'document upload' feature on its...             525
13  Bose said it was decided at the Left Front mee...             881
14  Guglielmo Marchetti of Notorious Pictures and ...             156
15  However, some reports suggest that there would...             379
16  While some scepticism remains about how far an...             625
17  US West Texas Intermediate (WTI) futures were ...             830
18  Samsung Electronics Co. unveiled a new range o...             740
19  While AR Rahman was the super judge of the sin...             262

# Average Number Of Words in Data 

In [10]:
def avg_word(sentence):    
    words = sentence.split()
    return (sum(len(word) for word in words)/len(words))

In [11]:
df1['Average_words'] = df1['STORY'].apply(lambda x: avg_word(x))
df1[['STORY','Average_words']].head(n=20)

STORY  Average_words
0   The roadshow and the filing of nomination pape...       4.722581
1   These vulnerabilities could have allowed hacke...       5.067416
2   "People will now be able to include music in t...       4.741935
3   Jersey is expected to have a good start at the...       4.352941
4   Xiaomi’s unveiling also hints at how Samsung i...       4.568000
5   Analysts at Edelweiss Securities Ltd point out...       5.846154
6   The directorial debut of Prithviraj Sukumaran ...       4.941176
7   Chrome is the most popular web browser, with a...       4.621212
8   "Maruti saw a sudden turn in its stock price a...       5.059829
9   Centrum has also raised TCS target prices high...       5.567901
10  While Mohanlal will play the titular role in B...       5.235294
11  Consequently, there has been an explosive grow...       5.325581
12  Expanding the 'document upload' feature on its...       5.717949
13  Bose said it was decided at the Left Front mee...       4.826667
14  Guglielmo Marchetti of Notorious Pictures and ...       5.541667
15  However, some reports suggest that there would...       5.196721
16  While some scepticism remains about how far an...       5.158416
17  US West Texas Intermediate (WTI) futures were ...       5.036765
18  Samsung Electronics Co. unveiled a new range o...       5.141667
19  While AR Rahman was the super judge of the sin...       4.652174

# Number Of Stop-Words  

In [12]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [13]:
df1['stopwords'] = df1['STORY'].apply(lambda x: len([x for x in x.split() if x in stop]))
df1[['STORY','stopwords']].head(n=20)

STORY  stopwords
0   The roadshow and the filing of nomination pape...         60
1   These vulnerabilities could have allowed hacke...         60
2   "People will now be able to include music in t...         43
3   Jersey is expected to have a good start at the...         19
4   Xiaomi’s unveiling also hints at how Samsung i...         48
5   Analysts at Edelweiss Securities Ltd point out...         12
6   The directorial debut of Prithviraj Sukumaran ...          5
7   Chrome is the most popular web browser, with a...         29
8   "Maruti saw a sudden turn in its stock price a...         34
9   Centrum has also raised TCS target prices high...         18
10  While Mohanlal will play the titular role in B...          5
11  Consequently, there has been an explosive grow...        163
12  Expanding the 'document upload' feature on its...         32
13  Bose said it was decided at the Left Front mee...         62
14  Guglielmo Marchetti of Notorious Pictures and ...         11
15  However, some reports suggest that there would...         21
16  While some scepticism remains about how far an...         41
17  US West Texas Intermediate (WTI) futures were ...         38
18  Samsung Electronics Co. unveiled a new range o...         37
19  While AR Rahman was the super judge of the sin...         12

# Hash_Tags in Data

In [14]:
df1['hastags'] = df1['STORY'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))
df1[['STORY','hastags']].head(n=20)

STORY  hastags
0   The roadshow and the filing of nomination pape...        0
1   These vulnerabilities could have allowed hacke...        0
2   "People will now be able to include music in t...        0
3   Jersey is expected to have a good start at the...        0
4   Xiaomi’s unveiling also hints at how Samsung i...        0
5   Analysts at Edelweiss Securities Ltd point out...        0
6   The directorial debut of Prithviraj Sukumaran ...        0
7   Chrome is the most popular web browser, with a...        0
8   "Maruti saw a sudden turn in its stock price a...        0
9   Centrum has also raised TCS target prices high...        0
10  While Mohanlal will play the titular role in B...        0
11  Consequently, there has been an explosive grow...        0
12  Expanding the 'document upload' feature on its...        0
13  Bose said it was decided at the Left Front mee...        0
14  Guglielmo Marchetti of Notorious Pictures and ...        0
15  However, some reports suggest that there would...        0
16  While some scepticism remains about how far an...        0
17  US West Texas Intermediate (WTI) futures were ...        0
18  Samsung Electronics Co. unveiled a new range o...        0
19  While AR Rahman was the super judge of the sin...        0

# Upper_Words in Data

In [15]:
df1['upper'] = df1['STORY'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
df1[['STORY','upper']].head()

STORY  upper
0  The roadshow and the filing of nomination pape...      5
1  These vulnerabilities could have allowed hacke...      6
2  "People will now be able to include music in t...      0
3  Jersey is expected to have a good start at the...      0
4  Xiaomi’s unveiling also hints at how Samsung i...      6

# Lower_Words in Data

In [16]:
df1['Lower'] = df1['STORY'].apply(lambda x: len([x for x in x.split() if x.islower()]))
df1[['STORY','Lower']].head()

STORY  Lower
0  The roadshow and the filing of nomination pape...    120
1  These vulnerabilities could have allowed hacke...    148
2  "People will now be able to include music in t...     80
3  Jersey is expected to have a good start at the...     33
4  Xiaomi’s unveiling also hints at how Samsung i...     95

# Removing Punctuation

In [17]:
df1['STORY'] = df1['STORY'].str.replace('[^\w\s]','')
df1['STORY'].head()

0    The roadshow and the filing of nomination pape...
1    These vulnerabilities could have allowed hacke...
2    People will now be able to include music in th...
3    Jersey is expected to have a good start at the...
4    Xiaomis unveiling also hints at how Samsung is...
Name: STORY, dtype: object

# Remove StopWords

In [18]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
df1['STORY'] = df1['STORY'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
df1['STORY'].head()

0    The roadshow filing nomination papers also att...
1    These vulnerabilities could allowed hackers ac...
2    People able include music videos Facebook Inst...
3    Jersey expected good start box office attentio...
4    Xiaomis unveiling also hints Samsung starting ...
Name: STORY, dtype: object

# Common Words Removal

In [19]:
comm = pd.Series(' '.join(df1['STORY']).split()).value_counts()[:10]
print(comm)

The         6215
said        2880
also        2026
India       1439
Congress    1338
BJP         1244
It          1192
In          1139
new         1126
I           1095
dtype: int64


In [20]:
comm = list(comm.index)
df1['STORY'] = df1['STORY'].apply(lambda x: " ".join(x for x in x.split() if x not in comm))
df1['STORY'].head()

0    roadshow filing nomination papers attempt show...
1    These vulnerabilities could allowed hackers ac...
2    People able include music videos Facebook Inst...
3    Jersey expected good start box office attentio...
4    Xiaomis unveiling hints Samsung starting lose ...
Name: STORY, dtype: object

# Rare Words Removal

In [21]:
comm2 = pd.Series(' '.join(df1['STORY']).split()).value_counts()[-10:]
print(comm2)

downfall                1
Ti                      1
appswith                1
hellbent                1
14000mAh                1
specificationsRealme    1
discharged              1
7621                    1
gaze                    1
payback                 1
dtype: int64


In [22]:
comm2 = list(comm2.index)
df1['STORY'] = df1['STORY'].apply(lambda x: " ".join(x for x in x.split() if x not in comm2))
df1['STORY'].head()

0    roadshow filing nomination papers attempt show...
1    These vulnerabilities could allowed hackers ac...
2    People able include music videos Facebook Inst...
3    Jersey expected good start box office attentio...
4    Xiaomis unveiling hints Samsung starting lose ...
Name: STORY, dtype: object

# Lemmatization

In [23]:
from textblob import Word
from textblob import TextBlob
df1['STORY'] = df1['STORY'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
df1['STORY'].head()

0    roadshow filing nomination paper attempt show ...
1    These vulnerability could allowed hacker acces...
2    People able include music video Facebook Insta...
3    Jersey expected good start box office attentio...
4    Xiaomis unveiling hint Samsung starting lose p...
Name: STORY, dtype: object

# N-grams

In [24]:
import nltk
nltk.download('punkt')
TextBlob(df1['STORY'][1]).ngrams(2)

[nltk_data] Downloading package punkt to C:\Users\Charan Deep
[nltk_data]     Singh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


[WordList(['These', 'vulnerability']),
 WordList(['vulnerability', 'could']),
 WordList(['could', 'allowed']),
 WordList(['allowed', 'hacker']),
 WordList(['hacker', 'access']),
 WordList(['access', 'sensitive']),
 WordList(['sensitive', 'information']),
 WordList(['information', 'take']),
 WordList(['take', 'control']),
 WordList(['control', 'number']),
 WordList(['number', 'smart']),
 WordList(['smart', 'home']),
 WordList(['home', 'device']),
 WordList(['device', 'platform']),
 WordList(['platform', 'like']),
 WordList(['like', 'door']),
 WordList(['door', 'lock']),
 WordList(['lock', 'security']),
 WordList(['security', 'camera']),
 WordList(['camera', 'thermostat']),
 WordList(['thermostat', 'NEW']),
 WordList(['NEW', 'DELHI']),
 WordList(['DELHI', 'September']),
 WordList(['September', '2016']),
 WordList(['2016', 'major']),
 WordList(['major', 'part']),
 WordList(['part', 'internet']),
 WordList(['internet', 'east']),
 WordList(['east', 'coast']),
 WordList(['coast', 'US']),
 Wo

In [25]:
TextBlob(df1['STORY'][1]).ngrams(3)

[WordList(['These', 'vulnerability', 'could']),
 WordList(['vulnerability', 'could', 'allowed']),
 WordList(['could', 'allowed', 'hacker']),
 WordList(['allowed', 'hacker', 'access']),
 WordList(['hacker', 'access', 'sensitive']),
 WordList(['access', 'sensitive', 'information']),
 WordList(['sensitive', 'information', 'take']),
 WordList(['information', 'take', 'control']),
 WordList(['take', 'control', 'number']),
 WordList(['control', 'number', 'smart']),
 WordList(['number', 'smart', 'home']),
 WordList(['smart', 'home', 'device']),
 WordList(['home', 'device', 'platform']),
 WordList(['device', 'platform', 'like']),
 WordList(['platform', 'like', 'door']),
 WordList(['like', 'door', 'lock']),
 WordList(['door', 'lock', 'security']),
 WordList(['lock', 'security', 'camera']),
 WordList(['security', 'camera', 'thermostat']),
 WordList(['camera', 'thermostat', 'NEW']),
 WordList(['thermostat', 'NEW', 'DELHI']),
 WordList(['NEW', 'DELHI', 'September']),
 WordList(['DELHI', 'September'

In [26]:
TextBlob(df1['STORY'][1]).ngrams(5)

[WordList(['These', 'vulnerability', 'could', 'allowed', 'hacker']),
 WordList(['vulnerability', 'could', 'allowed', 'hacker', 'access']),
 WordList(['could', 'allowed', 'hacker', 'access', 'sensitive']),
 WordList(['allowed', 'hacker', 'access', 'sensitive', 'information']),
 WordList(['hacker', 'access', 'sensitive', 'information', 'take']),
 WordList(['access', 'sensitive', 'information', 'take', 'control']),
 WordList(['sensitive', 'information', 'take', 'control', 'number']),
 WordList(['information', 'take', 'control', 'number', 'smart']),
 WordList(['take', 'control', 'number', 'smart', 'home']),
 WordList(['control', 'number', 'smart', 'home', 'device']),
 WordList(['number', 'smart', 'home', 'device', 'platform']),
 WordList(['smart', 'home', 'device', 'platform', 'like']),
 WordList(['home', 'device', 'platform', 'like', 'door']),
 WordList(['device', 'platform', 'like', 'door', 'lock']),
 WordList(['platform', 'like', 'door', 'lock', 'security']),
 WordList(['like', 'door', 

# Term frequency

In [27]:
tf1 = (df1['STORY'][1:2]).apply(lambda x: pd.value_counts(x.split(" "))).sum(axis = 0).reset_index()
tf1.columns = ['STORY','tf']
tf1

STORY  tf
0     device   5
1   platform   3
2     hacker   3
3   internet   3
4      These   3
..       ...  ..
78  Guardian   1
79       NEW   1
80      know   1
81      port   1
82       CNN   1

[83 rows x 2 columns]

# Inverse Document Frequency

In [28]:
for i,word in enumerate(tf1['STORY']):
    tf1.loc[i, 'idf'] = np.log(df1.shape[0]/(len(df1[df1['STORY'].str.contains(word)])))

tf1

STORY  tf       idf
0     device   5  2.643327
1   platform   3  3.022640
2     hacker   3  4.573237
3   internet   3  3.920581
4      These   3  3.833570
..       ...  ..       ...
78  Guardian   1  5.826000
79       NEW   1  3.971440
80      know   1  2.661933
81      port   1  1.341116
82       CNN   1  7.617760

[83 rows x 3 columns]

# Term Frequency – Inverse Document Frequency

In [29]:
tf1['tfidf'] = tf1['tf'] * tf1['idf']
tf1

STORY  tf       idf      tfidf
0     device   5  2.643327  13.216637
1   platform   3  3.022640   9.067919
2     hacker   3  4.573237  13.719711
3   internet   3  3.920581  11.761744
4      These   3  3.833570  11.500710
..       ...  ..       ...        ...
78  Guardian   1  5.826000   5.826000
79       NEW   1  3.971440   3.971440
80      know   1  2.661933   2.661933
81      port   1  1.341116   1.341116
82       CNN   1  7.617760   7.617760

[83 rows x 4 columns]

In [30]:
df1['STORY']

0       roadshow filing nomination paper attempt show ...
1       These vulnerability could allowed hacker acces...
2       People able include music video Facebook Insta...
3       Jersey expected good start box office attentio...
4       Xiaomis unveiling hint Samsung starting lose p...
                              ...                        
6097    Based video game franchise name Sonic Hedgehog...
6098    seven state neglected decade sends onetwo memb...
6099    Shanthnu made announcement Twitter shared pict...
6100    Rock Jason Statham reprise role Fast Furious f...
6101    But unlike past development never caught 3D TV...
Name: STORY, Length: 6102, dtype: object

In [31]:
print(df1['STORY'][0])

roadshow filing nomination paper attempt show strength ruling eastern UP region several minister ally party Varanasi filing nomination expected Friday 17 18 Lok Sabha seat region 2014 losing Azamgarh Samajwadi Party patriarch Mulayam Singh Yadav repeated performance 2017 assembly poll returned power Uttar Pradesh gap 15 year leader Modi visit Varanasi every month meet resident last five year Varanasi least 30 time Finance minister Arun Jaitley tweeted Modis roadshow culminated customary Ganga aarti express one indicationthat PM well way repeating even increasing 2014 victory margin


In [32]:
print(df1['STORY'][5])

Analysts Edelweiss Securities Ltd point increasing prevalence generic drug weigh pharmaceutical growth Regulatory intervention drug approval factor influencing sector unless sale seasonal illness drug see rise


In [33]:
from sklearn.model_selection import train_test_split

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
from sklearn.pipeline import Pipeline

In [36]:
from sklearn.svm import LinearSVC

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
from sklearn.ensemble import RandomForestClassifier

In [39]:
from sklearn.preprocessing import MinMaxScaler

In [40]:
from sklearn import metrics

In [41]:
from sklearn.neighbors import KNeighborsClassifier

In [42]:
from nltk.tokenize import TweetTokenizer

In [43]:
#tfidf = TfidfVectorizer()
#Train = tfidf.fit_transform(df1['STORY'])
#Test  = tfidf.fit_transform(df2['STORY'])

In [44]:
tokenizer = TweetTokenizer()

In [45]:
vectorizer = TfidfVectorizer(ngram_range=(1, 2), lowercase=True, tokenizer=tokenizer.tokenize)

In [46]:
full_text = list(df1['STORY'].values) + list(df2['STORY'].values)

In [47]:
vectorizer.fit(full_text)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 2), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<bound method TweetTokenizer.tokenize of <nltk.tokenize.casual.TweetTokenizer object at 0x0000023422E98048>>,
                use_idf=True, vocabulary=None)

In [48]:
train_vectorized = vectorizer.transform(df1['STORY'])

In [49]:
test_vectorized = vectorizer.transform(df2['STORY'])

In [50]:
X = train_vectorized

In [51]:
y = df1[['SECTION']]

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

# Logistic

In [53]:
log_pipe_line = Pipeline([('log',LogisticRegression())])

In [54]:
log_pipe_line.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('log',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=100,
                                    multi_class='warn', n_jobs=None,
                                    penalty='l2', random_state=None,
                                    solver='warn', tol=0.0001, verbose=0,
                                    warm_start=False))],
         verbose=False)

In [55]:
pred_log = log_pipe_line.predict(X_test)

In [56]:
print(metrics.classification_report(y_test,pred_log))

              precision    recall  f1-score   support

           0       0.98      0.91      0.95       425
           1       0.92      0.99      0.95       672
           2       0.95      0.98      0.96       455
           3       0.99      0.90      0.94       279

    accuracy                           0.95      1831
   macro avg       0.96      0.94      0.95      1831
weighted avg       0.95      0.95      0.95      1831



In [57]:
metrics.confusion_matrix(y_test,pred_log)

array([[387,  22,  15,   1],
       [  3, 662,   6,   1],
       [  2,   9, 444,   0],
       [  1,  26,   2, 250]], dtype=int64)

In [58]:
metrics.accuracy_score(y_test,pred_log)

0.9519388312397596

In [59]:
Test_data_log = log_pipe_line.predict(test_vectorized)

In [60]:
Test_data_log

array([2, 3, 2, ..., 1, 2, 2], dtype=int64)

In [61]:
len(Test_data_log)

1526

# Random Forest

In [62]:
rf_pipe_line = Pipeline([('rf',RandomForestClassifier())])

In [63]:
rf_pipe_line.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('rf',
                 RandomForestClassifier(bootstrap=True, class_weight=None,
                                        criterion='gini', max_depth=None,
                                        max_features='auto',
                                        max_leaf_nodes=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1, min_samples_split=2,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=10, n_jobs=None,
                                        oob_score=False, random_state=None,
                                        verbose=0, warm_start=False))],
         verbose=False)

In [64]:
pred_rf = rf_pipe_line.predict(X_test)

In [65]:
print(metrics.classification_report(y_test,pred_rf))

              precision    recall  f1-score   support

           0       0.95      0.88      0.91       425
           1       0.91      0.91      0.91       672
           2       0.83      0.96      0.89       455
           3       0.95      0.82      0.88       279

    accuracy                           0.90      1831
   macro avg       0.91      0.89      0.90      1831
weighted avg       0.90      0.90      0.90      1831



In [66]:
metrics.confusion_matrix(y_test,pred_rf)

array([[373,  25,  24,   3],
       [  5, 610,  48,   9],
       [ 10,   9, 436,   0],
       [  6,  28,  16, 229]], dtype=int64)

In [67]:
metrics.accuracy_score(y_test,pred_rf)

0.9000546149645002

# KNN 

In [68]:
knn_pipe_line = Pipeline([('knn',(KNeighborsClassifier()))])

In [69]:
knn_pipe_line.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('knn',
                 KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                      metric='minkowski', metric_params=None,
                                      n_jobs=None, n_neighbors=5, p=2,
                                      weights='uniform'))],
         verbose=False)

In [70]:
pred_knn=knn_pipe_line.predict(X_test)

In [71]:
print(metrics.classification_report(y_test,pred_knn))

              precision    recall  f1-score   support

           0       0.91      0.96      0.93       425
           1       0.91      0.97      0.94       672
           2       0.99      0.87      0.93       455
           3       0.94      0.91      0.93       279

    accuracy                           0.93      1831
   macro avg       0.94      0.93      0.93      1831
weighted avg       0.93      0.93      0.93      1831



In [72]:
metrics.confusion_matrix(y_test,pred_knn)

array([[406,  15,   2,   2],
       [ 12, 649,   2,   9],
       [ 24,  29, 396,   6],
       [  6,  17,   1, 255]], dtype=int64)

In [73]:
metrics.accuracy_score(y_test,pred_knn)

0.9317312943746586

# SVM

In [74]:
svm_pipe_line = Pipeline([('svm',(LinearSVC()))])

In [75]:
svm_pipe_line.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('svm',
                 LinearSVC(C=1.0, class_weight=None, dual=True,
                           fit_intercept=True, intercept_scaling=1,
                           loss='squared_hinge', max_iter=1000,
                           multi_class='ovr', penalty='l2', random_state=None,
                           tol=0.0001, verbose=0))],
         verbose=False)

In [76]:
svm_pred = svm_pipe_line.predict(X_test)

In [77]:
print(metrics.classification_report(y_test,svm_pred))

              precision    recall  f1-score   support

           0       0.99      0.94      0.96       425
           1       0.96      0.97      0.97       672
           2       0.95      0.99      0.97       455
           3       0.99      0.96      0.97       279

    accuracy                           0.97      1831
   macro avg       0.97      0.97      0.97      1831
weighted avg       0.97      0.97      0.97      1831



In [78]:
metrics.confusion_matrix(y_test,svm_pred)

array([[401,  14,   9,   1],
       [  4, 653,  13,   2],
       [  2,   3, 450,   0],
       [  0,  10,   2, 267]], dtype=int64)

In [79]:
metrics.accuracy_score(y_test,svm_pred)

0.9672310212998362

In [80]:
svm_pred = svm_pipe_line.predict(test_vectorized)

In [81]:
svm_pred

array([2, 3, 2, ..., 1, 0, 2], dtype=int64)

In [84]:
len(svm_pred)

1526

In [85]:
svm_pred

array([2, 3, 2, ..., 1, 0, 2], dtype=int64)

In [86]:
submit = pd.DataFrame({'Predictions': svm_pred })

submit.to_csv('News_Category_Submission.csv',index=False)